name: attestation
description: extract and sign provenance and SBOM files 
inputs:
  digest_artifact_prefix:
    default: digest-
  artifact_prefix:
    required: true
  image:
    description: |
      The image name component in a fully qualified image. For reference:
      ghcr.io/<repo>/<image>:<tag>
    required: true
  repo:
    description: |
      The repository component in a fully qualified image. For reference:
      ghcr.io/<repo>/<image>:<tag>
    required: true
  arch:
    default: amd64
  GH_TOKEN:
    description: |
      The GitHub token with permission to publish images to ghcr.
    required: true
runs:
  using: composite
  steps: 
      - name: Install cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      - name: Install the crane command
        shell: bash
        run: |
          set -e
          mkdir -p "${CRANE_PATH}"
          curl -sL "https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/go-containerregistry_Linux_x86_64.tar.gz" -o "${CRANE_PATH}/crane.tar.gz"
          echo "${CRANE_CHECKSUM} ${CRANE_PATH}/crane.tar.gz" | sha256sum -c
          tar xvf "${CRANE_PATH}/crane.tar.gz" -C "${CRANE_PATH}"
          rm "${CRANE_PATH}/crane.tar.gz"
          echo "CRANE_PATH=${CRANE_PATH}" >> "$GITHUB_ENV"
        env:
          CRANE_PATH: ${{ runner.temp }}/crane
          CRANE_VERSION: v0.20.5
          CRANE_CHECKSUM: ad4cd9af2568c62c97e346de6d1295ee8c6ce3341f7b71cf02d41292b4532680
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ inputs.GH_TOKEN }}
      - name: Download all digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ${{ runner.temp }}/digests
          pattern: ${{ inputs.digest_artifact_prefix }}${{ inputs.image }}-*
          merge-multiple: true
      - name: Retrieve digest
        id: retrieve-digest
        working-directory: ${{ runner.temp }}/digests
        shell: bash
        run: |
          set -e
          DIGEST=$(cat ${INPUTS_IMAGE}-${INPUTS_ARCH}.txt)
          echo "DIGEST=${DIGEST}" >> "$GITHUB_OUTPUT"
        env:
          INPUTS_IMAGE: ${{ inputs.image }}
          INPUTS_ARCH: ${{ inputs.arch }}
      - name: Find attestation digest
        id: attestation-digest
        shell: bash
        run: |
          set -e
          DIGEST=$(${CRANE_PATH}/crane manifest ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${DIGEST} \
          | jq -r '.manifests[]
            | select(.annotations["vnd.docker.reference.type"] == "attestation-manifest")
            | .digest')
          echo "ATTESTATION_MANIFEST_DIGEST=${DIGEST}" >> "$GITHUB_OUTPUT"
        env:
          INPUTS_REPO: ${{ inputs.repo }}
          INPUTS_IMAGE: ${{ inputs.image }}
          DIGEST: ${{ steps.retrieve-digest.outputs.DIGEST }}
      - name: Find provenance manifest digest
        id: provenance-digest
        shell: bash
        run: |
          set -e
          DIGEST=$(${CRANE_PATH}/crane manifest ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${ATTESTATION_MANIFEST_DIGEST} |
                      jq -r '.layers[]
                        | select(.annotations["in-toto.io/predicate-type"] == "https://slsa.dev/provenance/v1")
                        | .digest')
          echo "PROVENANCE_DIGEST=${DIGEST}" >> "$GITHUB_OUTPUT"
        env:
          INPUTS_REPO: ${{ inputs.repo }}
          INPUTS_IMAGE: ${{ inputs.image }}
          ATTESTATION_MANIFEST_DIGEST: ${{ steps.attestation-digest.outputs.ATTESTATION_MANIFEST_DIGEST }}
      - name: Find SBOM manifest layer digest
        id: sbom-digest
        shell: bash
        run: |
          set -e
          DIGEST=$(${CRANE_PATH}/crane manifest ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${ATTESTATION_MANIFEST_DIGEST} |  \
            jq '.layers | map(select(.annotations["in-toto.io/predicate-type"] == "https://spdx.dev/Document")) | map(.digest) | join(" ")')
          echo "SBOM_DIGEST=${DIGEST}" >> "$GITHUB_OUTPUT"
        env:
          INPUTS_REPO: ${{ inputs.repo }}
          INPUTS_IMAGE: ${{ inputs.image }}
          ATTESTATION_MANIFEST_DIGEST: ${{ steps.attestation-digest.outputs.ATTESTATION_MANIFEST_DIGEST }}

      # We need to upload provenance and SBOM files, plus their signatures under the GitHub Release page.
      # Moreover, the files have to be named in a certain way.
      # This is required by [ossf](https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases)
      - name: Download provenance and SBOM files
        shell: bash
        run: |
          set -e
          ${CRANE_PATH}/crane blob ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${PROVENANCE_DIGEST} \
            > ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-provenance.intoto.jsonl
          ${CRANE_PATH}/crane blob ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${SBOM_DIGEST} \
            > ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-sbom.json
        env:
          INPUTS_REPO: ${{ inputs.repo }}
          INPUTS_IMAGE: ${{ inputs.image }}
          INPUTS_ARTIFACT_PREFIX: ${{ inputs.artifact_prefix }}
          INPUTS_ARCH: ${{ inputs.arch }}
          PROVENANCE_DIGEST: ${{ steps.provenance-digest.outputs.PROVENANCE_DIGEST }}
          SBOM_DIGEST: ${{ steps.sbom-digest.outputs.SBOM_DIGEST }}
      - name: Sign provenance and SBOM files
        shell: bash
        run: |
          set -e
          cosign sign-blob --yes \
            --bundle ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-provenance.intoto.jsonl.bundle.sigstore \
            ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-provenance.intoto.jsonl
          cosign verify-blob \
            --bundle ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-provenance.intoto.jsonl.bundle.sigstore \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity="${{ github.server_url }}/${GITHUB_WORKFLOW_REF}" \
            ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-provenance.intoto.jsonl

          cosign sign-blob --yes \
            --bundle ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-sbom.json.bundle.sigstore \
            ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-sbom.json
          cosign verify-blob \
            --bundle ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-sbom.json.bundle.sigstore \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --certificate-identity="${{ github.server_url }}/${GITHUB_WORKFLOW_REF}" \
            ${INPUTS_ARTIFACT_PREFIX}${INPUTS_IMAGE}-attestation-${INPUTS_ARCH}-sbom.json
        env:
          INPUTS_ARTIFACT_PREFIX: ${{ inputs.artifact_prefix }}
          INPUTS_IMAGE: ${{ inputs.image }}
          INPUTS_ARCH: ${{ inputs.arch }}
      - name: Upload SBOMs as artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: attestation-${{ inputs.artifact_prefix }}${{ inputs.image }}-${{ inputs.arch }}
          path: ${{ inputs.artifact_prefix }}${{ inputs.image }}-attestation-${{ inputs.arch }}*
