fail_fast: false
minimum_pre_commit_version: '0'
repos:
  # more info on the usage: https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
  - repo: https://github.com/golangci/golangci-lint
    rev: 8f3b0c7ed018e57905fbd873c697e0b1ede605a5 # v2.11.4
    hooks:
      - id: golangci-lint-full
        language_version: 1.26.1
        stages: [pre-commit]
      - id: golangci-lint-fmt
        language_version: 1.26.0
        stages: [pre-commit]
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: dedddc3dab021fee0392f43eda027abbc273cf22 # v1.4.0
    hooks:
      - id: clang-format
        args:
          - --version=19
      - id: clang-tidy
        args:
          - --version=19
          - --checks=.clang-tidy
        files: ^bpf/.*\.c$
  - repo: https://github.com/yoheimuta/protolint
    rev: 67278bf4e14fdfc8bdafef823b8e76eb403ed9ba # v0.56.4
    hooks:
      - id: protolint
