fail_fast: false
minimum_pre_commit_version: '0'
repos:
  # more info on the usage: https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
  - repo: https://github.com/golangci/golangci-lint
    rev: 6008b81b81c690c046ffc3fd5bce896da715d5fd # v2.11.3
    hooks:
      - id: golangci-lint-full
        language_version: 1.26.1
        stages: [pre-commit]
      - id: golangci-lint-fmt
        language_version: 1.26.0
        stages: [pre-commit]
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: 525ac64394b766f8e9d2fcde75572217b9ff9286 # v1.1.13
    hooks:
      - id: clang-format
        args:
          - --version=19
      - id: clang-tidy
        args:
          - --version=19
          - --checks=.clang-tidy
        files: ^bpf/.*\.c$
  - repo: https://github.com/yoheimuta/protolint
    rev: 67278bf4e14fdfc8bdafef823b8e76eb403ed9ba # v0.56.4
    hooks:
      - id: protolint
