# Number of parallel VMs to run
parallel: 4
# kernel versions to test
kernel_versions:
    - v5.10.251
    - v5.15.201
    - v6.1.167
    - v6.6.130
    - v6.12.78
    - v6.17.12
    - v6.18.17
    - v6.19.7
