apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
    {{- include "runtime-enforcer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
      {{- include "runtime-enforcer.selectorLabels" . | nindent 8 }}
      {{- with .Values.operator.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
      {{- with .Values.operator.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClass.name }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - args: 
        - --wp-status-reconciler-agent-grpc-port={{ .Values.agent.grpcExporterPort }}
        - --wp-status-reconciler-update-interval={{ .Values.operator.wpStatusUpdateInterval }}
        - --wp-status-reconciler-agent-label-selector={{ include "runtime-enforcer.agent.labelSelectorString" . }}
        - --wp-status-reconciler-agent-grpc-mtls-cert-dir={{ include "runtime-enforcer.grpc.certDir" . }}
        {{- toYaml .Values.operator.args | nindent 8 }}
        command:
        - /operator
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- with .Values.operator.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.operator.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.operator.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs/
            name: webhook-certs
            readOnly: true
          - name: grpc-certs
            mountPath: {{ include "runtime-enforcer.grpc.certDir" . }}
            readOnly: true
      volumes:
        - name: webhook-certs
          csi:
            driver: "csi.cert-manager.io"
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: {{ include "runtime-enforcer.caIssuerName" . }}
              csi.cert-manager.io/issuer-kind: Issuer
              csi.cert-manager.io/dns-names: {{ include "runtime-enforcer.fullname" . }}-mutating-webhook.{{ .Release.Namespace }}.svc
        - name: grpc-certs
          csi:
            driver: "csi.cert-manager.io"
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: {{ include "runtime-enforcer.caIssuerName" . }}
              csi.cert-manager.io/issuer-kind: Issuer
              csi.cert-manager.io/dns-names: "runtime-enforcer-operator"
      securityContext: {{- toYaml .Values.operator.podSecurityContext | nindent
        8 }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "runtime-enforcer.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
