//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeIssue) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.NodeIssue"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ViolationRecord) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.ViolationRecord"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicy) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicyExecutables) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicyExecutables"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicyList) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicyProposal) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicyProposal"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicyProposalList) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicyProposalList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicyProposalSpec) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicyProposalSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicyRules) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicyRules"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicySpec) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadPolicyStatus) OpenAPIModelName() string {
	return "com.github.rancher-sandbox.runtime-enforcer.api.v1alpha1.WorkloadPolicyStatus"
}
