// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyState int32

const (
	PolicyState_POLICY_STATE_UNSPECIFIED PolicyState = 0
	// Policy present, loaded and actively running.
	PolicyState_POLICY_STATE_READY PolicyState = 1
	// Agent attempted to load/apply policy and it failed.
	PolicyState_POLICY_STATE_ERROR PolicyState = 2
)

// Enum value maps for PolicyState.
var (
	PolicyState_name = map[int32]string{
		0: "POLICY_STATE_UNSPECIFIED",
		1: "POLICY_STATE_READY",
		2: "POLICY_STATE_ERROR",
	}
	PolicyState_value = map[string]int32{
		"POLICY_STATE_UNSPECIFIED": 0,
		"POLICY_STATE_READY":       1,
		"POLICY_STATE_ERROR":       2,
	}
)

func (x PolicyState) Enum() *PolicyState {
	p := new(PolicyState)
	*p = x
	return p
}

func (x PolicyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (PolicyState) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[0]
}

func (x PolicyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyState.Descriptor instead.
func (PolicyState) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type PolicyMode int32

const (
	PolicyMode_POLICY_MODE_UNSPECIFIED PolicyMode = 0
	// Policy monitor mode
	PolicyMode_POLICY_MODE_MONITOR PolicyMode = 1
	// Policy protect mode
	PolicyMode_POLICY_MODE_PROTECT PolicyMode = 2
)

// Enum value maps for PolicyMode.
var (
	PolicyMode_name = map[int32]string{
		0: "POLICY_MODE_UNSPECIFIED",
		1: "POLICY_MODE_MONITOR",
		2: "POLICY_MODE_PROTECT",
	}
	PolicyMode_value = map[string]int32{
		"POLICY_MODE_UNSPECIFIED": 0,
		"POLICY_MODE_MONITOR":     1,
		"POLICY_MODE_PROTECT":     2,
	}
)

func (x PolicyMode) Enum() *PolicyMode {
	p := new(PolicyMode)
	*p = x
	return p
}

func (x PolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (PolicyMode) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[1]
}

func (x PolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyMode.Descriptor instead.
func (PolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type ContainerMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CgroupID      uint64                 `protobuf:"varint,3,opt,name=CgroupID,proto3" json:"CgroupID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMeta) Reset() {
	*x = ContainerMeta{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMeta) ProtoMessage() {}

func (x *ContainerMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMeta.ProtoReflect.Descriptor instead.
func (*ContainerMeta) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerMeta) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ContainerMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerMeta) GetCgroupID() uint64 {
	if x != nil {
		return x.CgroupID
	}
	return 0
}

type PodMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,4,opt,name=WorkloadName,proto3" json:"WorkloadName,omitempty"`
	WorkloadType  string                 `protobuf:"bytes,5,opt,name=WorkloadType,proto3" json:"WorkloadType,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodMeta) Reset() {
	*x = PodMeta{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodMeta) ProtoMessage() {}

func (x *PodMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodMeta.ProtoReflect.Descriptor instead.
func (*PodMeta) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PodMeta) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *PodMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodMeta) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *PodMeta) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

func (x *PodMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type PodView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *PodMeta               `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The key is the container ID
	Containers    map[string]*ContainerMeta `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodView) Reset() {
	*x = PodView{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodView) ProtoMessage() {}

func (x *PodView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodView.ProtoReflect.Descriptor instead.
func (*PodView) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PodView) GetMeta() *PodMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PodView) GetContainers() map[string]*ContainerMeta {
	if x != nil {
		return x.Containers
	}
	return nil
}

// ListPodCacheRequest is the request for listing the pod cache.
type ListPodCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodCacheRequest) Reset() {
	*x = ListPodCacheRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodCacheRequest) ProtoMessage() {}

func (x *ListPodCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodCacheRequest.ProtoReflect.Descriptor instead.
func (*ListPodCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

// ListPodCacheResponse is the response containing the pod cache.
type ListPodCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*PodView             `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodCacheResponse) Reset() {
	*x = ListPodCacheResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodCacheResponse) ProtoMessage() {}

func (x *ListPodCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodCacheResponse.ProtoReflect.Descriptor instead.
func (*ListPodCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListPodCacheResponse) GetPods() []*PodView {
	if x != nil {
		return x.Pods
	}
	return nil
}

type ListPoliciesStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusRequest) Reset() {
	*x = ListPoliciesStatusRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusRequest) ProtoMessage() {}

func (x *ListPoliciesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

type PolicyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PolicyState            `protobuf:"varint,1,opt,name=state,proto3,enum=runtimeenforcer.agent.v1.PolicyState" json:"state,omitempty"`
	Mode          PolicyMode             `protobuf:"varint,2,opt,name=mode,proto3,enum=runtimeenforcer.agent.v1.PolicyMode" json:"mode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStatus) Reset() {
	*x = PolicyStatus{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatus) ProtoMessage() {}

func (x *PolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatus.ProtoReflect.Descriptor instead.
func (*PolicyStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyStatus) GetState() PolicyState {
	if x != nil {
		return x.State
	}
	return PolicyState_POLICY_STATE_UNSPECIFIED
}

func (x *PolicyStatus) GetMode() PolicyMode {
	if x != nil {
		return x.Mode
	}
	return PolicyMode_POLICY_MODE_UNSPECIFIED
}

func (x *PolicyStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPoliciesStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Policies      map[string]*PolicyStatus `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusResponse) Reset() {
	*x = ListPoliciesStatusResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusResponse) ProtoMessage() {}

func (x *ListPoliciesStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListPoliciesStatusResponse) GetPolicies() map[string]*PolicyStatus {
	if x != nil {
		return x.Policies
	}
	return nil
}

type ScrapeViolationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeViolationsRequest) Reset() {
	*x = ScrapeViolationsRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeViolationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeViolationsRequest) ProtoMessage() {}

func (x *ScrapeViolationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeViolationsRequest.ProtoReflect.Descriptor instead.
func (*ScrapeViolationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

type ViolationRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PodName        string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName  string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ExecutablePath string                 `protobuf:"bytes,4,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	NodeName       string                 `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Action         string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	PolicyName     string                 `protobuf:"bytes,7,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ViolationRecord) Reset() {
	*x = ViolationRecord{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViolationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViolationRecord) ProtoMessage() {}

func (x *ViolationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViolationRecord.ProtoReflect.Descriptor instead.
func (*ViolationRecord) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ViolationRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ViolationRecord) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ViolationRecord) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ViolationRecord) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *ViolationRecord) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ViolationRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ViolationRecord) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

type ScrapeViolationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Violations    []*ViolationRecord     `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeViolationsResponse) Reset() {
	*x = ScrapeViolationsResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeViolationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeViolationsResponse) ProtoMessage() {}

func (x *ScrapeViolationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeViolationsResponse.ProtoReflect.Descriptor instead.
func (*ScrapeViolationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ScrapeViolationsResponse) GetViolations() []*ViolationRecord {
	if x != nil {
		return x.Violations
	}
	return nil
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x18runtimeenforcer.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\rContainerMeta\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bCgroupID\x18\x03 \x01(\x04R\bCgroupID\"\x95\x02\n" +
	"\aPodMeta\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tNamespace\x18\x03 \x01(\tR\tNamespace\x12\"\n" +
	"\fWorkloadName\x18\x04 \x01(\tR\fWorkloadName\x12\"\n" +
	"\fWorkloadType\x18\x05 \x01(\tR\fWorkloadType\x12E\n" +
	"\x06Labels\x18\x06 \x03(\v2-.runtimeenforcer.agent.v1.PodMeta.LabelsEntryR\x06Labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\aPodView\x125\n" +
	"\x04meta\x18\x01 \x01(\v2!.runtimeenforcer.agent.v1.PodMetaR\x04meta\x12Q\n" +
	"\n" +
	"containers\x18\x02 \x03(\v21.runtimeenforcer.agent.v1.PodView.ContainersEntryR\n" +
	"containers\x1af\n" +
	"\x0fContainersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.runtimeenforcer.agent.v1.ContainerMetaR\x05value:\x028\x01\"\x15\n" +
	"\x13ListPodCacheRequest\"M\n" +
	"\x14ListPodCacheResponse\x125\n" +
	"\x04pods\x18\x01 \x03(\v2!.runtimeenforcer.agent.v1.PodViewR\x04pods\"\x1b\n" +
	"\x19ListPoliciesStatusRequest\"\x9f\x01\n" +
	"\fPolicyStatus\x12;\n" +
	"\x05state\x18\x01 \x01(\x0e2%.runtimeenforcer.agent.v1.PolicyStateR\x05state\x128\n" +
	"\x04mode\x18\x02 \x01(\x0e2$.runtimeenforcer.agent.v1.PolicyModeR\x04mode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe1\x01\n" +
	"\x1aListPoliciesStatusResponse\x12^\n" +
	"\bpolicies\x18\x01 \x03(\v2B.runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntryR\bpolicies\x1ac\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.runtimeenforcer.agent.v1.PolicyStatusR\x05value:\x028\x01\"\x19\n" +
	"\x17ScrapeViolationsRequest\"\x8c\x02\n" +
	"\x0fViolationRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12'\n" +
	"\x0fexecutable_path\x18\x04 \x01(\tR\x0eexecutablePath\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1f\n" +
	"\vpolicy_name\x18\a \x01(\tR\n" +
	"policyName\"e\n" +
	"\x18ScrapeViolationsResponse\x12I\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2).runtimeenforcer.agent.v1.ViolationRecordR\n" +
	"violations*[\n" +
	"\vPolicyState\x12\x1c\n" +
	"\x18POLICY_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12POLICY_STATE_READY\x10\x01\x12\x16\n" +
	"\x12POLICY_STATE_ERROR\x10\x02*[\n" +
	"\n" +
	"PolicyMode\x12\x1b\n" +
	"\x17POLICY_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POLICY_MODE_MONITOR\x10\x01\x12\x17\n" +
	"\x13POLICY_MODE_PROTECT\x10\x022\x81\x03\n" +
	"\rAgentObserver\x12\x81\x01\n" +
	"\x12ListPoliciesStatus\x123.runtimeenforcer.agent.v1.ListPoliciesStatusRequest\x1a4.runtimeenforcer.agent.v1.ListPoliciesStatusResponse\"\x00\x12o\n" +
	"\fListPodCache\x12-.runtimeenforcer.agent.v1.ListPodCacheRequest\x1a..runtimeenforcer.agent.v1.ListPodCacheResponse\"\x00\x12{\n" +
	"\x10ScrapeViolations\x121.runtimeenforcer.agent.v1.ScrapeViolationsRequest\x1a2.runtimeenforcer.agent.v1.ScrapeViolationsResponse\"\x00B>Z<github.com/neuvector/runtime-enforcer/proto/agent/v1;agentv1b\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(PolicyState)(0),                   // 0: runtimeenforcer.agent.v1.PolicyState
	(PolicyMode)(0),                    // 1: runtimeenforcer.agent.v1.PolicyMode
	(*ContainerMeta)(nil),              // 2: runtimeenforcer.agent.v1.ContainerMeta
	(*PodMeta)(nil),                    // 3: runtimeenforcer.agent.v1.PodMeta
	(*PodView)(nil),                    // 4: runtimeenforcer.agent.v1.PodView
	(*ListPodCacheRequest)(nil),        // 5: runtimeenforcer.agent.v1.ListPodCacheRequest
	(*ListPodCacheResponse)(nil),       // 6: runtimeenforcer.agent.v1.ListPodCacheResponse
	(*ListPoliciesStatusRequest)(nil),  // 7: runtimeenforcer.agent.v1.ListPoliciesStatusRequest
	(*PolicyStatus)(nil),               // 8: runtimeenforcer.agent.v1.PolicyStatus
	(*ListPoliciesStatusResponse)(nil), // 9: runtimeenforcer.agent.v1.ListPoliciesStatusResponse
	(*ScrapeViolationsRequest)(nil),    // 10: runtimeenforcer.agent.v1.ScrapeViolationsRequest
	(*ViolationRecord)(nil),            // 11: runtimeenforcer.agent.v1.ViolationRecord
	(*ScrapeViolationsResponse)(nil),   // 12: runtimeenforcer.agent.v1.ScrapeViolationsResponse
	nil,                                // 13: runtimeenforcer.agent.v1.PodMeta.LabelsEntry
	nil,                                // 14: runtimeenforcer.agent.v1.PodView.ContainersEntry
	nil,                                // 15: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	13, // 0: runtimeenforcer.agent.v1.PodMeta.Labels:type_name -> runtimeenforcer.agent.v1.PodMeta.LabelsEntry
	3,  // 1: runtimeenforcer.agent.v1.PodView.meta:type_name -> runtimeenforcer.agent.v1.PodMeta
	14, // 2: runtimeenforcer.agent.v1.PodView.containers:type_name -> runtimeenforcer.agent.v1.PodView.ContainersEntry
	4,  // 3: runtimeenforcer.agent.v1.ListPodCacheResponse.pods:type_name -> runtimeenforcer.agent.v1.PodView
	0,  // 4: runtimeenforcer.agent.v1.PolicyStatus.state:type_name -> runtimeenforcer.agent.v1.PolicyState
	1,  // 5: runtimeenforcer.agent.v1.PolicyStatus.mode:type_name -> runtimeenforcer.agent.v1.PolicyMode
	15, // 6: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.policies:type_name -> runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry
	16, // 7: runtimeenforcer.agent.v1.ViolationRecord.timestamp:type_name -> google.protobuf.Timestamp
	11, // 8: runtimeenforcer.agent.v1.ScrapeViolationsResponse.violations:type_name -> runtimeenforcer.agent.v1.ViolationRecord
	2,  // 9: runtimeenforcer.agent.v1.PodView.ContainersEntry.value:type_name -> runtimeenforcer.agent.v1.ContainerMeta
	8,  // 10: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry.value:type_name -> runtimeenforcer.agent.v1.PolicyStatus
	7,  // 11: runtimeenforcer.agent.v1.AgentObserver.ListPoliciesStatus:input_type -> runtimeenforcer.agent.v1.ListPoliciesStatusRequest
	5,  // 12: runtimeenforcer.agent.v1.AgentObserver.ListPodCache:input_type -> runtimeenforcer.agent.v1.ListPodCacheRequest
	10, // 13: runtimeenforcer.agent.v1.AgentObserver.ScrapeViolations:input_type -> runtimeenforcer.agent.v1.ScrapeViolationsRequest
	9,  // 14: runtimeenforcer.agent.v1.AgentObserver.ListPoliciesStatus:output_type -> runtimeenforcer.agent.v1.ListPoliciesStatusResponse
	6,  // 15: runtimeenforcer.agent.v1.AgentObserver.ListPodCache:output_type -> runtimeenforcer.agent.v1.ListPodCacheResponse
	12, // 16: runtimeenforcer.agent.v1.AgentObserver.ScrapeViolations:output_type -> runtimeenforcer.agent.v1.ScrapeViolationsResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
