name: container-build
description: build/sign an image and publish its digest in artifact
inputs:
  digest_artifact_prefix:
    description: the prefix of the artifact filename
    default: digest-
  arch:
    description: |
      List of target architectures to build.
    default: amd64
  dockerfile:
    description: |
      The dockerfile to build
    default: Dockerfile
  image:
    description: |
      The image name component in a fully qualified image. For reference:
      ghcr.io/<repo>/<image>:<tag>
    required: true
  repo:
    description: |
      The repository component in a fully qualified image. For reference:
      ghcr.io/<repo>/<image>:<tag>
    required: true
  GH_TOKEN:
    description: |
      The GitHub token with permission to publish images to ghcr.
    required: true
runs:
  using: composite
  steps: 
    - name: Setup QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      with:
        image: tonistiigi/binfmt:qemu-v10.0.4
        cache-image: false
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.GH_TOKEN }}
    - name: Install cosign
      uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
      with:
        images: ghcr.io/${{ inputs.repo }}/${{ inputs.image }}
    - name: Build and push ${{ inputs.image }} for ${{ inputs.arch }}
      id: build-image
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/${{ inputs.arch }}
        push: true
        sbom: true
        provenance: mode=max
        tags: ghcr.io/${{ inputs.repo }}/${{ inputs.image }}
        outputs: |
          type=image,push=true,push-by-digest=true,name-canonical=true
    # We need to disable the new bundle format enabled by default since
    # cosign v3.x.x because some verification tools (e.g. slsactl, hauler and old
    # cosign) are not able to properly verify the signatures using this
    # new format
    - name: Sign container image with cosign v2 signature format
      shell: bash
      run: |
        cosign sign --yes --new-bundle-format=false --use-signing-config=false \
          ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${STEPS_BUILD_IMAGE_OUTPUTS_DIGEST}
      env:
        INPUTS_REPO: ${{ inputs.repo }}
        INPUTS_IMAGE: ${{ inputs.image }}
        STEPS_BUILD_IMAGE_OUTPUTS_DIGEST: ${{ steps.build-image.outputs.digest }}

    - name: Sign container image with cosign v3 signature format
      shell: bash
      run: |
        cosign sign --yes --new-bundle-format=true --use-signing-config=true \
          ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${STEPS_BUILD_IMAGE_OUTPUTS_DIGEST}
      env:
        INPUTS_REPO: ${{ inputs.repo }}
        INPUTS_IMAGE: ${{ inputs.image }}
        STEPS_BUILD_IMAGE_OUTPUTS_DIGEST: ${{ steps.build-image.outputs.digest }}

    - name: Verify container image signature
      shell: bash
      run: |
        cosign verify \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity="${{ github.server_url }}/${GITHUB_WORKFLOW_REF}" \
          ghcr.io/${INPUTS_REPO}/${INPUTS_IMAGE}@${STEPS_BUILD_IMAGE_OUTPUTS_DIGEST}
      env:
        INPUTS_REPO: ${{ inputs.repo }}
        INPUTS_IMAGE: ${{ inputs.image }}
        STEPS_BUILD_IMAGE_OUTPUTS_DIGEST: ${{ steps.build-image.outputs.digest }}

    - name: Export digest
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${STEPS_BUILD_IMAGE_OUTPUTS_DIGEST}"
        echo "${digest}" > "${{ runner.temp }}/digests/${INPUTS_IMAGE}-${INPUTS_ARCH}.txt"
      env:
        STEPS_BUILD_IMAGE_OUTPUTS_DIGEST: ${{ steps.build-image.outputs.digest }}
        INPUTS_IMAGE: ${{ inputs.image }}
        INPUTS_ARCH: ${{ inputs.arch }}

    - name: Upload digest
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ inputs.digest_artifact_prefix }}${{ inputs.image }}-${{ inputs.arch }}
        path: ${{ runner.temp }}/digests/*.txt
        retention-days: 1
