= Runtime-Enforcer Learning Mode Configuration

== Overview

Runtime-Enforcer can be configured to operate in learning mode, which allows it to observe process executions in your workloads and learns the executable paths that run. Then, it will create or update a `WorkloadPolicyProposal` in the workload namespace with the list of observed executables.

== Configuration Options
By default, Runtime-Enforcer starts in *learning* mode for **all namespaces**:

```yaml
learning:
  enabled: true
  namespaceSelector: ""
```

You can adjust this behaviour at install/upgrade time:

- Disable behaviour learning entirely. Enforcement defined by `WorkloadPolicy` will continue to work, but no new `WorkloadPolicyProposal` will be generated:
+
```bash
helm upgrade --install runtime-enforcer runtime-enforcer/runtime-enforcer \
  --namespace runtime-enforcer \
  --set learning.enabled=false
```

- Restrict learning to specific namespaces using a label selector:
+
```bash
helm upgrade --install runtime-enforcer runtime-enforcer/runtime-enforcer \
  --namespace runtime-enforcer \
  --set learning.namespaceSelector="env=prod"
```

When `learning.enabled=true`, Runtime-Enforcer will create or update `WorkloadPolicyProposal`
objects only for workloads in namespaces matching `learning.namespaceSelector`.
