apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-agent
  labels:
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "runtime-enforcer.agent.labelSelector" . | nindent 6 }}
  updateStrategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
      {{- include "runtime-enforcer.agent.labelSelector" . | nindent 8 }}
      {{- with .Values.agent.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: agent
      {{- with .Values.agent.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClass.name }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - args:
        {{- if .Values.telemetry.tracing }}
        - --enable-tracing
        {{- end }}
        {{- if .Values.learning.enabled }}
        - --enable-learning
        {{- end }}
        {{- if .Values.learning.namespaceSelector }}
        - --learning-namespace-selector={{ .Values.learning.namespaceSelector }}
        {{- else if .Values.learning.namespaceSelectorObject }}
        - --learning-namespace-selector={{ .Values.learning.namespaceSelectorObject | toJson }}
        {{- end }}
        - --grpc-port={{ .Values.agent.grpcExporterPort }}
        - --grpc-mtls-cert-dir={{ include "runtime-enforcer.grpc.certDir" . }}
        - --log-level={{ .Values.agent.logLevel }}
        {{- toYaml .Values.agent.args | nindent 8 }}
        command:
        - /agent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      {{- if or .Values.telemetry.metrics .Values.telemetry.tracing }}
      {{- if eq .Values.telemetry.mode "custom" }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{.Values.telemetry.custom.endpoint}}
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: {{ .Values.telemetry.custom.insecure | default false | quote }}
      {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorCertificateSecret }}
        - name: OTEL_EXPORTER_OTLP_CERTIFICATE
          value: /tmp/otel-collector-certs/ca.crt 
      {{- end }}
      {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorClientCertificateSecret }}
        - name: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
          value: /tmp/otel-collector-client-certs/tls.crt
        - name: OTEL_EXPORTER_OTLP_CLIENT_KEY
          value: /tmp/otel-collector-client-certs/tls.key
      {{- end }}
      {{- end }}
      {{- end }}
        {{- with .Values.agent.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
        name: agent
        startupProbe:
          httpGet:
            path: /readyz
            port: 8081
          # we give 45s (5s delay + 8 attempts every 5s) for the startup probe to succeed
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        resources: {{- toYaml .Values.agent.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.agent.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - name: nri-socket
          mountPath: /var/run/nri/
          mountPropagation: HostToContainer
          readOnly: true
        - name: grpc-certs
          mountPath: {{ include "runtime-enforcer.grpc.certDir" . }}
          readOnly: true
      hostPID: {{ .Values.agent.hostPID }}
      securityContext: {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "runtime-enforcer.fullname" . }}-agent
      terminationGracePeriodSeconds: 10
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: nri-socket
        hostPath:
          path: {{ .Values.agent.nriSocketPath }}
      - name: grpc-certs
        csi:
          driver: "csi.cert-manager.io"
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/issuer-name: {{ include "runtime-enforcer.caIssuerName" . }}
            csi.cert-manager.io/issuer-kind: Issuer
            csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}
