name: bpf tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
      - name: Install system dependencies for eBPF build
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libelf-dev \
            clang \
            llvm \
            libbpf-dev
      - name: Generate eBPF code
        run: |
          make generate-ebpf
          go test -c ./internal/bpf/... -o tester
      - name: Run eBPF test
        run: |
          make test-bpf
      - name: Validate bpf tests using bpfvalidator
        uses: ./.github/actions/bpfvalidator
        with:
          args: |
            --config=${{ github.workspace }}/bpfvalidator-${{ matrix.arch }}-config.yaml --cmd=${{ github.workspace }}/tester -test.v
          arch: ${{ matrix.arch }}
