name: redhat-linux-10-e2e
on:
 release:
   types: published
 schedule:
   - cron: "15 0 * * 5"
     timezone: "America/New_York"
 workflow_dispatch:
jobs:
  run-e2e-test:
    permissions:
      contents: read
    name: Run e2e test on RHEL 10.2
    runs-on: redhat
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Run e2e test
      run: |
        go clean -testcache
        E2E_USE_EXISTING_CLUSTER=true E2E_SKIP_DEPENDENCIES= go test -v -timeout 20m ./test/e2e/
